version: '3.4'

services:
    catalogdb:
        image: mongo:6.0.4

    basketdb:
        image: redis:7.0.8-alpine

    discountdb:
        image: postgres:15.2-alpine

    orderdb:
        image: arm64v8/mysql:8.0.32

    pgadmin:
        image: dpage/pgadmin4

    portainer:
        image: portainer/portainer-ce:alpine

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Dockerfile

    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: Services/Basket/Basket.API/Dockerfile

    discount.api:
        image: ${DOCKER_REGISTRY-}discountapi
        build:
            context: .
            dockerfile: Services/Discount/Discount.API/Dockerfile

    discount.grpc:
        image: ${DOCKER_REGISTRY-}discountgrpc
        build:
            context: .
            dockerfile: Services/Discount/Discount.Grpc/Dockerfile

    ordering.api:
        image: ${DOCKER_REGISTRY-}orderingapi
        build:
            context: .
            dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
    catalogdbdata:
    portainerdata:
    discountdbdata:
    pgadmindata:


