version: '3.4'

services:
  catalogdb:
    image: mongo:6.0.4

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  catalogdbdata:
